version: '3.1'
services:
  stats-service:
    build: ewm-stats-service/stats-service
    image: ewm-stats-service-image
    container_name: ewm-stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine

    container_name: stats-db-container

    environment:
        - POSTGRES_DB=ewm-stats-db
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root




  #ewm-service:
    #ports:
      #- "8080:8080"

  #ewm-db:
    #image: postgres:14-alpine