version: '3.1'
services:

  main-service:
    build: ewm-main-service

    image: main-service-image

    container_name: main-service-container

    ports:
      - "8080:8080"

    depends_on:
      - ewm-main-db
      - stats-service

    restart: on-failure

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-db:5432/ewm-main-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - STATS_SERVER_URL=http://stats-service:9090


  stats-service:
    build: ewm-stats-service/stats-service

    image: stats-service-image

    container_name: stats-service-container

    ports:
      - "9090:9090"

    depends_on:
      - stats-db

    restart: on-failure

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine

    container_name: stats-db-container

    ports:
      - "6541:5432"

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=stats-db

  ewm-main-db:
    image: postgres:14-alpine

    container_name: ewm-main-db-container

    ports:
      - "6542:5432"

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-main-db